//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackLogic.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class measuring
    {
        public System.DateTime date_time { get; set; }
        public decimal frequency { get; set; }
        public float pdbm { get; set; }
        public int id_measurings { get; set; }
    }
}
